
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.beans
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["itemNum"].IsNumber) { throw new SerializationException(); }  ItemNum = _buf["itemNum"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new beans.Item(_buf);
    }

    /// <summary>
    /// 道具Id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具数量
    /// </summary>
    public readonly int ItemNum;
   
    public const int __ID__ = -515569794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "itemNum:" + ItemNum + ","
        + "}";
    }
}
}

