
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DrChapter : Luban.BeanBase
{
    public DrChapter(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["chapter_title"].IsString) { throw new SerializationException(); }  ChapterTitle = _buf["chapter_title"]; }
        { if(!_buf["chapter_figure"].IsString) { throw new SerializationException(); }  ChapterFigure = _buf["chapter_figure"]; }
        { if(!_buf["chapter_figure_x"].IsNumber) { throw new SerializationException(); }  ChapterFigureX = _buf["chapter_figure_x"]; }
        { if(!_buf["chapter_figure_y"].IsNumber) { throw new SerializationException(); }  ChapterFigureY = _buf["chapter_figure_y"]; }
        { if(!_buf["next_chapter"].IsNumber) { throw new SerializationException(); }  NextChapter = _buf["next_chapter"]; }
        { var __json0 = _buf["level_id"]; if(!__json0.IsArray) { throw new SerializationException(); } LevelId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  LevelId.Add(__v0); }   }
    }

    public static DrChapter DeserializeDrChapter(JSONNode _buf)
    {
        return new DrChapter(_buf);
    }

    /// <summary>
    /// 章节id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 章节名称<br/>（多语言key）
    /// </summary>
    public readonly string ChapterTitle;
    /// <summary>
    /// 章节图片<br/>（配置资源名称）
    /// </summary>
    public readonly string ChapterFigure;
    /// <summary>
    /// x轴切分数量
    /// </summary>
    public readonly int ChapterFigureX;
    /// <summary>
    /// y轴切分数量
    /// </summary>
    public readonly int ChapterFigureY;
    /// <summary>
    /// 下一章章节id
    /// </summary>
    public readonly int NextChapter;
    /// <summary>
    /// 章节中关卡id
    /// </summary>
    public readonly System.Collections.Generic.List<int> LevelId;
   
    public const int __ID__ = 867732415;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "chapterTitle:" + ChapterTitle + ","
        + "chapterFigure:" + ChapterFigure + ","
        + "chapterFigureX:" + ChapterFigureX + ","
        + "chapterFigureY:" + ChapterFigureY + ","
        + "nextChapter:" + NextChapter + ","
        + "levelId:" + Luban.StringUtil.CollectionToString(LevelId) + ","
        + "}";
    }
}
}

