
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DrLevel : Luban.BeanBase
{
    public DrLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["next_level"].IsNumber) { throw new SerializationException(); }  NextLevel = _buf["next_level"]; }
        { if(!_buf["level_figure"].IsString) { throw new SerializationException(); }  LevelFigure = _buf["level_figure"]; }
        { if(!_buf["level_figure_x"].IsNumber) { throw new SerializationException(); }  LevelFigureX = _buf["level_figure_x"]; }
        { if(!_buf["level_figure_y"].IsNumber) { throw new SerializationException(); }  LevelFigureY = _buf["level_figure_y"]; }
        { if(!_buf["difficulty_tier"].IsNumber) { throw new SerializationException(); }  DifficultyTier = _buf["difficulty_tier"]; }
        { if(!_buf["out_of_place_number"].IsNumber) { throw new SerializationException(); }  OutOfPlaceNumber = _buf["out_of_place_number"]; }
        { var __json0 = _buf["m_distance_range"]; if(!__json0.IsArray) { throw new SerializationException(); } MDistanceRange = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MDistanceRange.Add(__v0); }   }
    }

    public static DrLevel DeserializeDrLevel(JSONNode _buf)
    {
        return new DrLevel(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 下一章章节id
    /// </summary>
    public readonly int NextLevel;
    /// <summary>
    /// 关卡图片<br/>（配置资源名称）
    /// </summary>
    public readonly string LevelFigure;
    /// <summary>
    /// x轴切分数量
    /// </summary>
    public readonly int LevelFigureX;
    /// <summary>
    /// y轴切分数量
    /// </summary>
    public readonly int LevelFigureY;
    /// <summary>
    /// 关卡难度<br/>1.普通<br/>2.困难
    /// </summary>
    public readonly int DifficultyTier;
    /// <summary>
    /// 至多{0}块在原位
    /// </summary>
    public readonly int OutOfPlaceNumber;
    /// <summary>
    /// 总曼哈顿距离范围<br/>（左闭右闭）
    /// </summary>
    public readonly System.Collections.Generic.List<int> MDistanceRange;
   
    public const int __ID__ = -737222794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nextLevel:" + NextLevel + ","
        + "levelFigure:" + LevelFigure + ","
        + "levelFigureX:" + LevelFigureX + ","
        + "levelFigureY:" + LevelFigureY + ","
        + "difficultyTier:" + DifficultyTier + ","
        + "outOfPlaceNumber:" + OutOfPlaceNumber + ","
        + "mDistanceRange:" + Luban.StringUtil.CollectionToString(MDistanceRange) + ","
        + "}";
    }
}
}

