
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbChapter TbChapter {get; }
    public TbLevel TbLevel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbChapter = new TbChapter(loader("tbchapter"));
        TbLevel = new TbLevel(loader("tblevel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbChapter.ResolveRef(this);
        TbLevel.ResolveRef(this);
    }
}

}
