
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbChapter
{
    private readonly System.Collections.Generic.Dictionary<int, DrChapter> _dataMap;
    private readonly System.Collections.Generic.List<DrChapter> _dataList;
    
    public TbChapter(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DrChapter>(count);
        _dataList = new System.Collections.Generic.List<DrChapter>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DrChapter _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.DrChapter.DeserializeDrChapter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DrChapter> DataMap => _dataMap;
    public System.Collections.Generic.List<DrChapter> DataList => _dataList;

    public DrChapter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DrChapter Get(int key) => _dataMap[key];
    public DrChapter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

