
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbLevel
{
    private readonly System.Collections.Generic.Dictionary<int, DrLevel> _dataMap;
    private readonly System.Collections.Generic.List<DrLevel> _dataList;
    
    public TbLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DrLevel>(count);
        _dataList = new System.Collections.Generic.List<DrLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DrLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.DrLevel.DeserializeDrLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DrLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<DrLevel> DataList => _dataList;

    public DrLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DrLevel Get(int key) => _dataMap[key];
    public DrLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

